from __future__ import annotations
import inspect as inspect
__all__ = ['debug', 'error', 'fatal', 'info', 'inspect', 'trace', 'warn']
def debug(logger, msg):
    ...
def error(logger, msg):
    ...
def fatal(logger, msg):
    ...
def info(logger, msg):
    ...
def trace(logger, msg):
    ...
def warn(logger, msg):
    ...
