from __future__ import annotations
__all__ = ['check_for_ros2_type_support', 'check_is_valid_ros2_msg_type', 'check_is_valid_srv_type']
def check_for_ros2_type_support(msg_or_srv_type):
    ...
def check_is_valid_ros2_msg_type(msg_type):
    ...
def check_is_valid_srv_type(srv_type):
    ...
