name: CI/CD Workflow

on:
  pull_request:
    branches:
      - '*'
      - '**'
  push:
    branches:
      - '*'
      - '**'
  release:
    types: [published]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    with:
      platform: ubuntu-22.04

  test-linux-gcc:
    uses: ./.github/workflows/test.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
      tool_chain: ${{ matrix.tool_chain }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            tool_chain: gcc-11
            image: ubuntu:jammy
          - platform: ubuntu-22.04-arm
            tool_chain: gcc-11
            image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: gcc-12
            image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: gcc-13
            image: ubuntu:jammy

    needs:
      - check

  test-linux-clang:
    uses: ./.github/workflows/test.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
      tool_chain: ${{ matrix.tool_chain }}
    strategy:
      matrix:
        include:
          # - platform: ubuntu-22.04-arm
          #   tool_chain: clang-15
          #   image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: clang-15
            image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: clang-16
            image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: clang-17
            image: ubuntu:jammy
          - platform: ubuntu-22.04
            tool_chain: clang-18
            image: ubuntu:jammy

    needs:
      - check

  test-windows:
    uses: ./.github/workflows/test-windows.yml
    with:
      run_platform: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: windows-2022
    needs:
      - check

  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
      tool_chain: ${{ matrix.tool_chain }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            tool_chain: gcc-11
            image: ubuntu:jammy

          - platform: ubuntu-22.04-arm
            tool_chain: gcc-11
            image: ubuntu:jammy
    needs:
      - test-linux-gcc
      - test-linux-clang
      - test-windows

  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      run_platform: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: windows-2022
    needs:
      - test-linux-gcc
      - test-linux-clang
      - test-windows